# Generated by Django 6.0.4 on 2026-04-16 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Предмет ЕГЭ',
                'verbose_name_plural': 'Предметы ЕГЭ',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=20, verbose_name='Код специальности')),
                ('faculty', models.CharField(max_length=255, verbose_name='Факультет')),
                ('profile', models.CharField(choices=[('IT', 'IT'), ('Наука', 'Наука'), ('Техника', 'Техника'), ('Экономика', 'Экономика'), ('Гуманитарные', 'Гуманитарные')], max_length=50, verbose_name='Профиль')),
                ('min_score', models.PositiveIntegerField(verbose_name='Минимальный балл')),
                ('avg_score', models.PositiveIntegerField(verbose_name='Средний балл')),
                ('budget_places', models.PositiveIntegerField(verbose_name='Бюджетных мест')),
                ('cost_per_year', models.PositiveIntegerField(verbose_name='Стоимость в год (руб.)')),
                ('years', models.PositiveSmallIntegerField(default=4, verbose_name='Срок обучения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.university', verbose_name='Университет')),
                ('subjects', models.ManyToManyField(to='programs.subject', verbose_name='Предметы ЕГЭ')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
    ]
