# Generated by Django 6.0.4 on 2026-04-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='degree',
            field=models.CharField(choices=[('bachelor', 'Бакалавриат'), ('master', 'Магистратура'), ('specialist', 'Специалитет'), ('college', 'Среднее профессиональное')], default='bachelor', max_length=20, verbose_name='Уровень подготовки'),
        ),
        migrations.AddField(
            model_name='program',
            name='study_form',
            field=models.CharField(choices=[('full_time', 'Очная'), ('part_time', 'Заочная'), ('evening', 'Очно-заочная')], default='full_time', max_length=20, verbose_name='Форма обучения'),
        ),
    ]
