# Generated by Django 6.0.4 on 2026-04-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_program_degree_program_study_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='paid_places',
            field=models.PositiveIntegerField(default=0, verbose_name='Платных мест'),
        ),
    ]
