# Generated by Django 6.0.4 on 2026-05-02 13:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_program_paid_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='subjects',
        ),
        migrations.CreateModel(
            name='AdmissionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Год приёма')),
                ('min_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальный балл')),
                ('avg_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Средний балл')),
                ('budget_places', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Бюджетные места')),
                ('paid_places', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Платные места')),
                ('cost_per_year', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость обучения в год')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_plans', to='programs.program', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'План приёма',
                'verbose_name_plural': 'Планы приёма',
                'ordering': ['-year'],
                'constraints': [models.UniqueConstraint(fields=('program', 'year'), name='unique_program_admission_year'), models.CheckConstraint(condition=models.Q(('year__gt', 0)), name='admission_year_positive'), models.CheckConstraint(condition=models.Q(('budget_places__gte', 0)), name='admission_budget_places_non_negative'), models.CheckConstraint(condition=models.Q(('paid_places__gte', 0)), name='admission_paid_places_non_negative'), models.CheckConstraint(condition=models.Q(('cost_per_year__gte', 0)), name='admission_cost_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='ProgramSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный предмет')),
                ('min_subject_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Минимальный балл по предмету')),
                ('group_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер группы')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_subjects', to='programs.program', verbose_name='Программа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_subjects', to='programs.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Предмет программы',
                'verbose_name_plural': 'Предметы программ',
                'constraints': [models.UniqueConstraint(fields=('program', 'subject'), name='unique_program_subject'), models.CheckConstraint(condition=models.Q(models.Q(('min_subject_score__gte', 0), ('min_subject_score__lte', 100)), ('min_subject_score__isnull', True), _connector='OR'), name='program_subject_score_between_0_100')],
            },
        ),
    ]
