# Generated by Django 6.0.4 on 2026-05-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_remove_program_subjects_admissionplan_programsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='subjects',
            field=models.ManyToManyField(related_name='programs', through='programs.ProgramSubject', to='programs.subject', verbose_name='Предметы ЕГЭ'),
        ),
    ]
