# Generated by Django 6.0.4 on 2026-05-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_program_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='avg_score',
        ),
        migrations.RemoveField(
            model_name='program',
            name='budget_places',
        ),
        migrations.RemoveField(
            model_name='program',
            name='cost_per_year',
        ),
        migrations.RemoveField(
            model_name='program',
            name='min_score',
        ),
        migrations.RemoveField(
            model_name='program',
            name='paid_places',
        ),
    ]
