# Generated by Django 6.0.4 on 2026-05-30 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_remove_program_avg_score_and_more'),
        ('universities', '0009_university_cited_by_count_university_h_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название кафедры')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название направления')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Код направления')),
                ('profile', models.CharField(blank=True, choices=[('IT', 'IT'), ('Наука', 'Наука'), ('Техника', 'Техника'), ('Экономика', 'Экономика'), ('Гуманитарные', 'Гуманитарные')], max_length=50, verbose_name='Профиль')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='programs.department', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Направление подготовки',
                'verbose_name_plural': 'Направления подготовки',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='programs.direction', verbose_name='Направление подготовки'),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Краткое название')),
                ('type', models.CharField(choices=[('institute', 'Институт'), ('faculty', 'Факультет'), ('school', 'Высшая школа'), ('other', 'Другое')], default='faculty', max_length=20, verbose_name='Тип')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='universities.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Институт/Факультет',
                'verbose_name_plural': 'Институты и факультеты',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='programs.faculty', verbose_name='Институт/Факультет'),
        ),
    ]
