# Generated by Django 6.0.4 on 2026-05-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_structure_faculty_department_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='profile',
        ),
    ]
