# Generated by Django 6.0.4 on 2026-05-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_remove_program_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='program',
            name='code',
        ),
        migrations.RemoveField(
            model_name='program',
            name='faculty',
        ),
    ]
