# Generated by Django 6.0.4 on 2026-05-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_remove_program_code_faculty_direction_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionplan',
            name='passing_score_budget',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Проходной балл (бюджет)'),
        ),
        migrations.AddField(
            model_name='admissionplan',
            name='passing_score_paid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Проходной балл (контракт)'),
        ),
    ]
