# Generated by Django 6.0.4 on 2026-05-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_add_passing_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='degree',
            field=models.CharField(choices=[('bachelor', 'Бакалавриат'), ('master', 'Магистратура'), ('specialist', 'Специалитет'), ('postgraduate', 'Аспирантура')], default='bachelor', max_length=20, verbose_name='Уровень подготовки'),
        ),
    ]
