# Generated by Django 6.0.4 on 2026-05-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_degree_replace_college_with_postgraduate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionplan',
            name='avg_score',
        ),
    ]
