# Generated by Django 6.0.4 on 2026-05-31 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0014_remove_admissionplan_avg_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directions', to='programs.department', verbose_name='Кафедра'),
        ),
    ]
