# Generated by Django 6.0.4 on 2026-05-31 10:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0015_alter_direction_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionplan',
            name='budget_places',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Бюджетные места'),
        ),
        migrations.AlterField(
            model_name='admissionplan',
            name='paid_places',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Платные места'),
        ),
        migrations.CreateModel(
            name='EntranceExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название испытания')),
                ('min_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальный балл')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_exams', to='programs.program', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Вступительное испытание',
                'verbose_name_plural': 'Вступительные испытания',
            },
        ),
    ]
