# Generated by Django 6.0.4 on 2026-05-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_alter_admissionplan_budget_places_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='programs', through='programs.ProgramSubject', to='programs.subject', verbose_name='Предметы ЕГЭ'),
        ),
    ]
