# Generated by Django 6.0.4 on 2026-05-31 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0017_alter_program_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directions', to='programs.faculty', verbose_name='Институт/Факультет'),
        ),
    ]
