# Generated by Django 6.0.4 on 2026-04-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, verbose_name='Дата')),
                ('event', models.CharField(max_length=255, verbose_name='Событие')),
                ('type', models.CharField(default='Дедлайн', max_length=50, verbose_name='Тип')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Дата приёмной кампании',
                'verbose_name_plural': 'Даты приёмной кампании',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('icon', models.CharField(default='info-circle', help_text='Например: buildings, calculator, trophy', max_length=50, verbose_name='Bootstrap-иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Правило приёма',
                'verbose_name_plural': 'Правила приёма',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Этап поступления',
                'verbose_name_plural': 'Этапы поступления',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Категория льготников')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Льготник',
                'verbose_name_plural': 'Льготники',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('desc', models.CharField(max_length=255, verbose_name='Описание')),
                ('quota', models.CharField(max_length=50, verbose_name='Квота')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория мест',
                'verbose_name_plural': 'Категории мест',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('section', models.CharField(choices=[('home', 'Главная страница'), ('guide', 'Справочник')], default='guide', max_length=20, verbose_name='Раздел')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вопрос и ответ',
                'verbose_name_plural': 'Вопросы и ответы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Документ')),
                ('type', models.CharField(choices=[('required', 'Обязательный'), ('optional', 'Дополнительный')], default='required', max_length=20, verbose_name='Тип')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['order'],
            },
        ),
    ]
