# Generated by Django 6.0.4 on 2026-04-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdmissionRule',
        ),
    ]
