# Generated by Django 6.0.4 on 2026-05-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_admissionrule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdmissionDeadline',
        ),
    ]
