# Generated by Django 6.0.4 on 2026-04-16 08:30

import apps.universities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='photo',
            field=models.ImageField(blank=True, help_text='Максимальный размер: 2 МБ. Рекомендуемые форматы: JPG, PNG.', null=True, upload_to='universities/', validators=[apps.universities.models.validate_image_size], verbose_name='Фотография'),
        ),
    ]
