# Generated by Django 6.0.4 on 2026-04-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='has_dormitory',
            field=models.BooleanField(default=False, help_text='Есть ли общежитие для студентов', verbose_name='Общежитие'),
        ),
        migrations.AddField(
            model_name='university',
            name='has_military',
            field=models.BooleanField(default=False, help_text='Есть ли военная кафедра', verbose_name='Военная кафедра'),
        ),
    ]
