# Generated by Django 6.0.4 on 2026-04-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_university_has_dormitory_university_has_military'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='university',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='university',
            name='full_name',
            field=models.CharField(blank=True, max_length=512, verbose_name='Полное название'),
        ),
        migrations.AddField(
            model_name='university',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='university',
            name='region',
            field=models.CharField(blank=True, max_length=150, verbose_name='Регион'),
        ),
    ]
