# Generated by Django 6.0.4 on 2026-04-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_university_address_university_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
    ]
