# Generated by Django 6.0.4 on 2026-04-30 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_openalex_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='cited_by_count',
        ),
        migrations.RemoveField(
            model_name='university',
            name='h_index',
        ),
        migrations.RemoveField(
            model_name='university',
            name='openalex_id',
        ),
        migrations.RemoveField(
            model_name='university',
            name='works_count',
        ),
        migrations.AlterField(
            model_name='university',
            name='has_dormitory',
            field=models.BooleanField(default=False, verbose_name='Общежитие'),
        ),
        migrations.AlterField(
            model_name='university',
            name='has_military',
            field=models.BooleanField(default=False, verbose_name='Военная кафедра'),
        ),
        migrations.CreateModel(
            name='UniversityResearchActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openalex_id', models.CharField(blank=True, max_length=32, verbose_name='OpenAlex ID')),
                ('works_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Публикаций')),
                ('cited_by_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цитирований')),
                ('h_index', models.PositiveIntegerField(blank=True, null=True, verbose_name='Индекс Хирша')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_activity', to='universities.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Научная активность',
                'verbose_name_plural': 'Научная активность университетов',
            },
        ),
    ]
