# Generated by Django 6.0.4 on 2026-05-01 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_remove_university_cited_by_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, verbose_name='Дата')),
                ('event', models.CharField(max_length=255, verbose_name='Событие')),
                ('type', models.CharField(default='Дедлайн', max_length=50, verbose_name='Тип')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='universities.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Дата приёмной кампании',
                'verbose_name_plural': 'Даты приёмной кампании',
                'ordering': ['order'],
            },
        ),
    ]
