# Generated by Django 6.0.4 on 2026-05-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0008_admissiondeadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='cited_by_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цитирований'),
        ),
        migrations.AddField(
            model_name='university',
            name='h_index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Индекс Хирша'),
        ),
        migrations.AddField(
            model_name='university',
            name='openalex_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='OpenAlex ID'),
        ),
        migrations.AddField(
            model_name='university',
            name='works_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Публикаций'),
        ),
        migrations.DeleteModel(
            name='UniversityResearchActivity',
        ),
    ]
